"""freight_ops_expansion

Revision ID: 20a2cbe54317
Revises: 808a347d150d
Create Date: 2026-06-22 09:29:18.473917
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20a2cbe54317'
down_revision: Union[str, None] = '808a347d150d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consignees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('appointment_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_consignees_tenant_id'), 'consignees', ['tenant_id'], unique=False)
    op.create_table('lanes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('default_mode', sa.Enum('ltl', 'tl', 'spot_bid', 'air_freight', name='loadmode'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_lanes_tenant_id'), 'lanes', ['tenant_id'], unique=False)
    op.create_table('rate_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.Enum('ltl', 'tl', 'spot_bid', 'air_freight', name='loadmode'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version')
    )
    op.create_index(op.f('ix_rate_cards_mode'), 'rate_cards', ['mode'], unique=False)
    op.create_index(op.f('ix_rate_cards_tenant_id'), 'rate_cards', ['tenant_id'], unique=False)
    op.create_table('accessorial_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('charge_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessorial_rules_rate_card_id'), 'accessorial_rules', ['rate_card_id'], unique=False)
    op.create_index(op.f('ix_accessorial_rules_tenant_id'), 'accessorial_rules', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('external_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('freight_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('external_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_documents_entity_id'), 'freight_documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_freight_documents_entity_type'), 'freight_documents', ['entity_type'], unique=False)
    op.create_index(op.f('ix_freight_documents_tenant_id'), 'freight_documents', ['tenant_id'], unique=False)
    op.create_table('freight_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('external_visible', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_events_entity_id'), 'freight_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_freight_events_entity_type'), 'freight_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_freight_events_event_type'), 'freight_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_freight_events_occurred_at'), 'freight_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_freight_events_tenant_id'), 'freight_events', ['tenant_id'], unique=False)
    op.create_table('rate_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('rate_card_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('rule_type', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('calculation', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_rules_rate_card_id'), 'rate_rules', ['rate_card_id'], unique=False)
    op.create_index(op.f('ix_rate_rules_tenant_id'), 'rate_rules', ['tenant_id'], unique=False)
    op.create_table('shippers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_shippers_tenant_id'), 'shippers', ['tenant_id'], unique=False)
    op.create_table('freight_shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('shipment_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('shipper_id', sa.String(length=36), nullable=True),
    sa.Column('consignee_id', sa.String(length=36), nullable=True),
    sa.Column('lane_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.Enum('ltl', 'tl', 'spot_bid', 'air_freight', name='loadmode'), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('equipment', sa.String(length=120), nullable=True),
    sa.Column('service_level', sa.String(length=120), nullable=True),
    sa.Column('weight_lb', sa.Float(), nullable=True),
    sa.Column('pallet_count', sa.Integer(), nullable=True),
    sa.Column('freight_class', sa.String(length=30), nullable=True),
    sa.Column('hazmat', sa.Boolean(), nullable=False),
    sa.Column('pickup_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_at', sa.DateTime(), nullable=True),
    sa.Column('actual_pickup_at', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('awb_number', sa.String(length=80), nullable=True),
    sa.Column('mawb_number', sa.String(length=80), nullable=True),
    sa.Column('hawb_number', sa.String(length=80), nullable=True),
    sa.Column('origin_airport', sa.String(length=8), nullable=True),
    sa.Column('destination_airport', sa.String(length=8), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensional_weight_kg', sa.Float(), nullable=True),
    sa.Column('chargeable_weight_kg', sa.Float(), nullable=True),
    sa.Column('uplift_at', sa.DateTime(), nullable=True),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('internal_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('client_charge', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['consignee_id'], ['consignees.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['shippers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'shipment_number')
    )
    op.create_index(op.f('ix_freight_shipments_mode'), 'freight_shipments', ['mode'], unique=False)
    op.create_index(op.f('ix_freight_shipments_shipment_number'), 'freight_shipments', ['shipment_number'], unique=False)
    op.create_index(op.f('ix_freight_shipments_tenant_id'), 'freight_shipments', ['tenant_id'], unique=False)
    op.create_table('freight_tenders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tender_number', sa.String(length=100), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('lane_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.Enum('ltl', 'tl', 'spot_bid', 'air_freight', name='loadmode'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'countered', 'accepted', 'rejected', 'expired', 'awarded', 'in_transit', 'delivered', 'invoiced', 'paid', 'disputed', 'closed', name='tenderstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('quoted_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('internal_cost', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('target_margin_pct', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tender_number')
    )
    op.create_index(op.f('ix_freight_tenders_mode'), 'freight_tenders', ['mode'], unique=False)
    op.create_index(op.f('ix_freight_tenders_shipment_id'), 'freight_tenders', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_freight_tenders_status'), 'freight_tenders', ['status'], unique=False)
    op.create_index(op.f('ix_freight_tenders_tenant_id'), 'freight_tenders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_freight_tenders_tender_number'), 'freight_tenders', ['tender_number'], unique=False)
    op.create_table('freight_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('quote_number', sa.String(length=100), nullable=False),
    sa.Column('tender_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('lane_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.Enum('ltl', 'tl', 'spot_bid', 'air_freight', name='loadmode'), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('internal_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('client_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('margin_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('calculation_input', sa.JSON(), nullable=False),
    sa.Column('calculation_trace', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['freight_tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'quote_number')
    )
    op.create_index(op.f('ix_freight_quotes_mode'), 'freight_quotes', ['mode'], unique=False)
    op.create_index(op.f('ix_freight_quotes_quote_number'), 'freight_quotes', ['quote_number'], unique=False)
    op.create_index(op.f('ix_freight_quotes_tenant_id'), 'freight_quotes', ['tenant_id'], unique=False)
    op.create_table('tender_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tender_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['freight_tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'revision_number')
    )
    op.create_index(op.f('ix_tender_revisions_tenant_id'), 'tender_revisions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tender_revisions_tender_id'), 'tender_revisions', ['tender_id'], unique=False)
    op.create_table('freight_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('tender_id', sa.String(length=36), nullable=True),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', 'sent', 'partially_paid', 'paid', 'past_due', 'on_hold', 'disputed', 'credited', 'voided', name='freightinvoicestatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('quoted_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_reference', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['freight_quotes.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['freight_tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'invoice_number')
    )
    op.create_index(op.f('ix_freight_invoices_invoice_number'), 'freight_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_freight_invoices_status'), 'freight_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_freight_invoices_tenant_id'), 'freight_invoices', ['tenant_id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('external_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['freight_quotes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_items_quote_id'), 'quote_line_items', ['quote_id'], unique=False)
    op.create_index(op.f('ix_quote_line_items_tenant_id'), 'quote_line_items', ['tenant_id'], unique=False)
    op.create_table('credit_adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('adjustment_number', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['freight_invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_adjustments_invoice_id'), 'credit_adjustments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_credit_adjustments_tenant_id'), 'credit_adjustments', ['tenant_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('opened_by_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('disputed_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['freight_invoices.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_invoice_id'), 'disputes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_disputes_tenant_id'), 'disputes', ['tenant_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['freight_invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_tenant_id'), 'invoice_line_items', ['tenant_id'], unique=False)
    # SQLite stores this enum as a VARCHAR and does not enforce its declared
    # length, so no schema change is required there. PostgreSQL uses a native
    # enum and needs each new role added explicitly.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'sales_quote_desk'")
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'dispatch_execution'")
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'billing_finance'")
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'readonly_client'")
        op.execute("ALTER TYPE role ADD VALUE IF NOT EXISTS 'readonly_partner'")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL enum values cannot be removed safely in place. Leaving the
    # additive role values behind keeps downgrades data-safe; SQLite requires
    # no role-column change.
    op.drop_index(op.f('ix_invoice_line_items_tenant_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_disputes_tenant_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_invoice_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_credit_adjustments_tenant_id'), table_name='credit_adjustments')
    op.drop_index(op.f('ix_credit_adjustments_invoice_id'), table_name='credit_adjustments')
    op.drop_table('credit_adjustments')
    op.drop_index(op.f('ix_quote_line_items_tenant_id'), table_name='quote_line_items')
    op.drop_index(op.f('ix_quote_line_items_quote_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_freight_invoices_tenant_id'), table_name='freight_invoices')
    op.drop_index(op.f('ix_freight_invoices_status'), table_name='freight_invoices')
    op.drop_index(op.f('ix_freight_invoices_invoice_number'), table_name='freight_invoices')
    op.drop_table('freight_invoices')
    op.drop_index(op.f('ix_tender_revisions_tender_id'), table_name='tender_revisions')
    op.drop_index(op.f('ix_tender_revisions_tenant_id'), table_name='tender_revisions')
    op.drop_table('tender_revisions')
    op.drop_index(op.f('ix_freight_quotes_tenant_id'), table_name='freight_quotes')
    op.drop_index(op.f('ix_freight_quotes_quote_number'), table_name='freight_quotes')
    op.drop_index(op.f('ix_freight_quotes_mode'), table_name='freight_quotes')
    op.drop_table('freight_quotes')
    op.drop_index(op.f('ix_freight_tenders_tender_number'), table_name='freight_tenders')
    op.drop_index(op.f('ix_freight_tenders_tenant_id'), table_name='freight_tenders')
    op.drop_index(op.f('ix_freight_tenders_status'), table_name='freight_tenders')
    op.drop_index(op.f('ix_freight_tenders_shipment_id'), table_name='freight_tenders')
    op.drop_index(op.f('ix_freight_tenders_mode'), table_name='freight_tenders')
    op.drop_table('freight_tenders')
    op.drop_index(op.f('ix_freight_shipments_tenant_id'), table_name='freight_shipments')
    op.drop_index(op.f('ix_freight_shipments_shipment_number'), table_name='freight_shipments')
    op.drop_index(op.f('ix_freight_shipments_mode'), table_name='freight_shipments')
    op.drop_table('freight_shipments')
    op.drop_index(op.f('ix_shippers_tenant_id'), table_name='shippers')
    op.drop_table('shippers')
    op.drop_index(op.f('ix_rate_rules_tenant_id'), table_name='rate_rules')
    op.drop_index(op.f('ix_rate_rules_rate_card_id'), table_name='rate_rules')
    op.drop_table('rate_rules')
    op.drop_index(op.f('ix_freight_events_tenant_id'), table_name='freight_events')
    op.drop_index(op.f('ix_freight_events_occurred_at'), table_name='freight_events')
    op.drop_index(op.f('ix_freight_events_event_type'), table_name='freight_events')
    op.drop_index(op.f('ix_freight_events_entity_type'), table_name='freight_events')
    op.drop_index(op.f('ix_freight_events_entity_id'), table_name='freight_events')
    op.drop_table('freight_events')
    op.drop_index(op.f('ix_freight_documents_tenant_id'), table_name='freight_documents')
    op.drop_index(op.f('ix_freight_documents_entity_type'), table_name='freight_documents')
    op.drop_index(op.f('ix_freight_documents_entity_id'), table_name='freight_documents')
    op.drop_table('freight_documents')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_accessorial_rules_tenant_id'), table_name='accessorial_rules')
    op.drop_index(op.f('ix_accessorial_rules_rate_card_id'), table_name='accessorial_rules')
    op.drop_table('accessorial_rules')
    op.drop_index(op.f('ix_rate_cards_tenant_id'), table_name='rate_cards')
    op.drop_index(op.f('ix_rate_cards_mode'), table_name='rate_cards')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_lanes_tenant_id'), table_name='lanes')
    op.drop_table('lanes')
    op.drop_index(op.f('ix_consignees_tenant_id'), table_name='consignees')
    op.drop_table('consignees')
    # ### end Alembic commands ###
