"""freight procurement workflow

Revision ID: 2453325027b0
Revises: 20a2cbe54317
Create Date: 2026-06-23 08:27:21.492206
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2453325027b0'
down_revision: Union[str, None] = '20a2cbe54317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == 'postgresql':
        op.execute("ALTER TYPE loadmode ADD VALUE IF NOT EXISTS 'small_parcel'")
        op.execute("ALTER TYPE loadmode ADD VALUE IF NOT EXISTS 'other'")
    op.create_table('carrier_compliance_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_id', 'document_type')
    )
    op.create_index(op.f('ix_carrier_compliance_documents_carrier_id'), 'carrier_compliance_documents', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_compliance_documents_tenant_id'), 'carrier_compliance_documents', ['tenant_id'], unique=False)
    op.create_table('freight_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_program', sa.String(length=255), nullable=True),
    sa.Column('contract_number', sa.String(length=120), nullable=True),
    sa.Column('origin', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('pickup_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_at', sa.DateTime(), nullable=True),
    sa.Column('quote_deadline', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.Enum('small_parcel', 'ltl', 'tl', 'spot_bid', 'air_freight', 'other', name='loadmode'), nullable=False),
    sa.Column('weight_lb', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('commodity', sa.String(length=255), nullable=False),
    sa.Column('hazmat', sa.Boolean(), nullable=False),
    sa.Column('refrigerated', sa.Boolean(), nullable=False),
    sa.Column('government_relevance', sa.Boolean(), nullable=False),
    sa.Column('sddc_relevance', sa.Boolean(), nullable=False),
    sa.Column('gfm_relevance', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('required_compliance_tags', sa.JSON(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sourcing', 'rfq_open', 'evaluating', 'awarded', 'closed', 'canceled', name='opportunitystatus'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('awarded_carrier_id', sa.String(length=36), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'opportunity_number')
    )
    op.create_index(op.f('ix_freight_opportunities_mode'), 'freight_opportunities', ['mode'], unique=False)
    op.create_index(op.f('ix_freight_opportunities_opportunity_number'), 'freight_opportunities', ['opportunity_number'], unique=False)
    op.create_index(op.f('ix_freight_opportunities_status'), 'freight_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_freight_opportunities_tenant_id'), 'freight_opportunities', ['tenant_id'], unique=False)
    op.create_table('opportunity_carriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('not_contacted', 'shortlisted', 'rfq_sent', 'responded', 'no_bid', 'quoted', 'awarded', 'rejected', name='opportunitycarrierstatus'), nullable=False),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('manual_adjustment', sa.Float(), nullable=False),
    sa.Column('rfq_subject', sa.String(length=255), nullable=True),
    sa.Column('rfq_body', sa.Text(), nullable=True),
    sa.Column('rfq_generated_at', sa.DateTime(), nullable=True),
    sa.Column('rfq_sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['freight_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'carrier_id')
    )
    op.create_index(op.f('ix_opportunity_carriers_carrier_id'), 'opportunity_carriers', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_opportunity_carriers_opportunity_id'), 'opportunity_carriers', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_carriers_status'), 'opportunity_carriers', ['status'], unique=False)
    op.create_index(op.f('ix_opportunity_carriers_tenant_id'), 'opportunity_carriers', ['tenant_id'], unique=False)
    op.create_table('carrier_bids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_carrier_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transit_days', sa.Float(), nullable=True),
    sa.Column('accessorials', sa.JSON(), nullable=False),
    sa.Column('fuel_surcharge', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('carrier_contact', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_carrier_id'], ['opportunity_carriers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['freight_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_bids_carrier_id'), 'carrier_bids', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_bids_opportunity_carrier_id'), 'carrier_bids', ['opportunity_carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_bids_opportunity_id'), 'carrier_bids', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_carrier_bids_tenant_id'), 'carrier_bids', ['tenant_id'], unique=False)
    op.create_table('freight_awards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('bid_id', sa.String(length=36), nullable=True),
    sa.Column('awarded_by_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('score_snapshot', sa.JSON(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bid_id'], ['carrier_bids.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['freight_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_freight_awards_carrier_id'), 'freight_awards', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_freight_awards_opportunity_id'), 'freight_awards', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_freight_awards_tenant_id'), 'freight_awards', ['tenant_id'], unique=False)
    op.add_column('carriers', sa.Column('tier', sa.String(length=40), nullable=False, server_default='standard'))
    op.add_column('carriers', sa.Column('classification', sa.String(length=40), nullable=False, server_default='carrier'))
    op.add_column('carriers', sa.Column('covered_modes', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('carriers', sa.Column('headquarters', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('carriers', sa.Column('regions_served', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('carriers', sa.Column('government_business', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carriers', sa.Column('sddc_registered', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carriers', sa.Column('gfm_approved', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carriers', sa.Column('dod_relevant', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carriers', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('carriers', sa.Column('primary_contact_name', sa.String(length=180), nullable=True))
    op.add_column('carriers', sa.Column('primary_contact_email', sa.String(length=255), nullable=True))
    op.add_column('carriers', sa.Column('primary_contact_phone', sa.String(length=60), nullable=True))
    op.add_column('carriers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('carriers', sa.Column('authority_status', sa.String(length=40), nullable=False, server_default='active'))
    op.add_column('carriers', sa.Column('insurance_expires_on', sa.Date(), nullable=True))
    op.add_column('carriers', sa.Column('hazmat_capable', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carriers', sa.Column('refrigerated_capable', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('carriers', sa.Column('relationship_status', sa.String(length=40), nullable=False, server_default='unknown'))
    op.add_column('carriers', sa.Column('compliance_status', sa.String(length=40), nullable=False, server_default='incomplete'))
    op.add_column('carriers', sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
    op.add_column('carriers', sa.Column('performance_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('carriers', sa.Column('prior_awards', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('carriers', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
    if dialect == 'postgresql':
        op.create_unique_constraint('uq_carriers_tenant_code', 'carriers', ['tenant_id', 'code'])
    op.add_column('contacts', sa.Column('carrier_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_contacts_carrier_id'), 'contacts', ['carrier_id'], unique=False)
    if dialect == 'postgresql':
        op.create_foreign_key('fk_contacts_carrier_id_carriers', 'contacts', 'carriers', ['carrier_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == 'postgresql':
        op.drop_constraint('fk_contacts_carrier_id_carriers', 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_carrier_id'), table_name='contacts')
    op.drop_column('contacts', 'carrier_id')
    if dialect == 'postgresql':
        op.drop_constraint('uq_carriers_tenant_code', 'carriers', type_='unique')
    op.drop_column('carriers', 'active')
    op.drop_column('carriers', 'prior_awards')
    op.drop_column('carriers', 'performance_score')
    op.drop_column('carriers', 'last_contacted_at')
    op.drop_column('carriers', 'compliance_status')
    op.drop_column('carriers', 'relationship_status')
    op.drop_column('carriers', 'refrigerated_capable')
    op.drop_column('carriers', 'hazmat_capable')
    op.drop_column('carriers', 'insurance_expires_on')
    op.drop_column('carriers', 'authority_status')
    op.drop_column('carriers', 'notes')
    op.drop_column('carriers', 'primary_contact_phone')
    op.drop_column('carriers', 'primary_contact_email')
    op.drop_column('carriers', 'primary_contact_name')
    op.drop_column('carriers', 'website')
    op.drop_column('carriers', 'dod_relevant')
    op.drop_column('carriers', 'gfm_approved')
    op.drop_column('carriers', 'sddc_registered')
    op.drop_column('carriers', 'government_business')
    op.drop_column('carriers', 'regions_served')
    op.drop_column('carriers', 'headquarters')
    op.drop_column('carriers', 'covered_modes')
    op.drop_column('carriers', 'classification')
    op.drop_column('carriers', 'tier')
    op.drop_index(op.f('ix_freight_awards_tenant_id'), table_name='freight_awards')
    op.drop_index(op.f('ix_freight_awards_opportunity_id'), table_name='freight_awards')
    op.drop_index(op.f('ix_freight_awards_carrier_id'), table_name='freight_awards')
    op.drop_table('freight_awards')
    op.drop_index(op.f('ix_carrier_bids_tenant_id'), table_name='carrier_bids')
    op.drop_index(op.f('ix_carrier_bids_opportunity_id'), table_name='carrier_bids')
    op.drop_index(op.f('ix_carrier_bids_opportunity_carrier_id'), table_name='carrier_bids')
    op.drop_index(op.f('ix_carrier_bids_carrier_id'), table_name='carrier_bids')
    op.drop_table('carrier_bids')
    op.drop_index(op.f('ix_opportunity_carriers_tenant_id'), table_name='opportunity_carriers')
    op.drop_index(op.f('ix_opportunity_carriers_status'), table_name='opportunity_carriers')
    op.drop_index(op.f('ix_opportunity_carriers_opportunity_id'), table_name='opportunity_carriers')
    op.drop_index(op.f('ix_opportunity_carriers_carrier_id'), table_name='opportunity_carriers')
    op.drop_table('opportunity_carriers')
    op.drop_index(op.f('ix_freight_opportunities_tenant_id'), table_name='freight_opportunities')
    op.drop_index(op.f('ix_freight_opportunities_status'), table_name='freight_opportunities')
    op.drop_index(op.f('ix_freight_opportunities_opportunity_number'), table_name='freight_opportunities')
    op.drop_index(op.f('ix_freight_opportunities_mode'), table_name='freight_opportunities')
    op.drop_table('freight_opportunities')
    op.drop_index(op.f('ix_carrier_compliance_documents_tenant_id'), table_name='carrier_compliance_documents')
    op.drop_index(op.f('ix_carrier_compliance_documents_carrier_id'), table_name='carrier_compliance_documents')
    op.drop_table('carrier_compliance_documents')
    # ### end Alembic commands ###
